# Generated by Django 3.2.4 on 2021-07-02 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210702_1500'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
